### ISSUE TITLE
Travis Error for PHP 5.3

### ISSUE THREAD

**Issue by dstuecken** [dstuecken/php7ify#2]
https://travis-ci.org/dstuecken/php7ify/jobs/660420373?utm_medium=notification&utm_source=email

**Comment by peter279k** [comment]
@dstuecken. It seems that it's the temporary failed build for `php-5.3` version on Travis CI build.

According to this [Travis CI build log](https://travis-ci.org/dstuecken/php7ify/builds/660421678?utm_medium=notification&utm_source=email), it's worked successfully.
